pipeline:
  test:
    image: hashicorp/terraform
    commands:
      - apk add make
      - make

  build:
    image: node:8.10-alpine
    commands:
        - printenv | sort
        - apk update && apk add zip
        - sed -i.bak "s/@TAG@/$DRONE_COMMIT_SHA/" index.js
        - zip cloudfront-directory-index.zip index.js

  s3:
    image: plugins/s3
    region: us-east-1
    acl: bucket-owner-full-control
    bucket: drone-us-east-1-224588347132
    source: cloudfront-directory-index.zip
    target: cloudfront-directory-index/
    when:
       branch: [ develop ]

  s3:
    image: plugins/s3
    region: us-east-1
    acl: bucket-owner-full-control
    bucket: drone-us-east-1-617683844790
    source: cloudfront-directory-index.zip
    target: cloudfront-directory-index/
    when:
       branch: [ master ]
